### ISSUE TITLE
hget google.com

### ISSUE THREAD

**Issue by bsonntag** [bevacqua/hget#3]
I cannot hget google.

When I run `hget google.com` I get the following output:

```
/home/ben/.nvm/v4.4.1/lib/node_modules/hget/cli:63
    throw new Error('Response body is empty.');
    ^

Error: Response body is empty.
    at Request.response [as _callback] (/home/ben/.nvm/v4.4.1/lib/node_modules/hget/cli:63:11)
    at Request.self.callback (/home/ben/.nvm/v4.4.1/lib/node_modules/hget/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/ben/.nvm/v4.4.1/lib/node_modules/hget/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/ben/.nvm/v4.4.1/lib/node_modules/hget/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

This also happens if I try `hget www.google.com` or `hget https://www.google.com/`.

**Comment by bevacqua** [comment]
Fixed in `3.0.1`. Only happened via the CLI.
